---
# This workflow integrates ShiftLeft NG SAST with GitHub
# Visit https://docs.shiftleft.io for help
name: ShiftLeft

on:
  push:
    branches: 
      - master    
  pull_request:
  workflow_dispatch:

jobs:
  NextGen-Static-Analyis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # We are building this application with Java 11
    - name: Setup Java JDK
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 11.0.x
    - name: Build and package with Gradle
      run: ./gradlew shadowJar
    - name: Download ShiftLeft CLI
      run: |
        curl https://cdn.shiftleft.io/download/sl > ${GITHUB_WORKSPACE}/sl && chmod a+rx ${GITHUB_WORKSPACE}/sl
    # ShiftLeft requires Java 1.8. Post the package step override the version
    - name: Setup Java JDK
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.8
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: NextGen Static Analysis
      run: ${GITHUB_WORKSPACE}/sl analyze --sca --app log4shell-vulnerable-app --tag branch=${{ github.head_ref || steps.extract_branch.outputs.branch }} --java --cpg ./build/libs/log4shell-vulnerable-app-all.jar
      env:
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
        
    - name: Create status check
      run: |
        sh shiftleft-pr-check.sh
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        GITHUB_REPO: "${{ github.repository }}"
        GITHUB_SHA: "${{ github.sha }}"
        GITHUB_REF: "${{ github.ref }}"
        SHIFTLEFT_ORG_ID: ${{ secrets.SHIFTLEFT_ORG_ID }}
        SHIFTLEFT_API_TOKEN: ${{ secrets.SHIFTLEFT_API_TOKEN }}
